import { generateStatement } from '../js/generatejs.js';
import { commentMarker } from './bfid.js';
import type { BackcodeSite, IfSetSite } from './collect.js';

/**
 * Where a site's DOM node is, relative to the owning patch-branch's `ref_elem`.
 *  - `ref-element`: the patch-branch's own ref element — `this.ref_elem`. Reached
 *    with no querySelector. Covers the custom element itself (root branch) and any
 *    site whose nearest enclosing element *is* the branch's ref element (a
 *    `b-unwrap b-if` branch anchors its content to the element the set sits in).
 *  - `bfid-element`: a descendant element, located via `sel_<bfid>()`.
 */
export type PatchTarget =
	| { kind: 'ref-element' }
	| { kind: 'bfid-element'; bfid: string };

export interface BfidSite {
	target: PatchTarget;
	backcode: BackcodeSite;
	// For 'print' sites: the ids of the two marker comments bracketing the range.
	// `target` is the print's parent element (the comments' DOM parent).
	comments?: { startId: string; endId: string };
}

/**
 * A qualifying `b-if`/`b-else-if`/`b-else` set, ready for codegen.
 *
 * `setId` (the leading marker's bfid) names every symbol the set generates:
 * the module-level `bfif_<setId>` snapshot, `branch_<setId>`, `renderIf_<setId>`,
 * `getCreatePatchBranch_<setId>`, and the `this.if_<setId>` / `this.if_pb_<setId>`
 * fields. `snapshot` is the `nodeToJS` literal of the whole `IfTNode`, taken
 * *after* all AST mutation so it carries the same bfids and print markers as the
 * server-rendered HTML.
 */
export interface IfSetPatchSite {
	/** Anchor for `renderIf_`'s swap — and the `ref_elem` handed to every child branch. */
	target: PatchTarget;
	ifSet: IfSetSite;
	setId: string;
	endId: string;
	snapshot: string;
	/** Live vars anywhere in the set's branch *content* (nested conditions included). */
	subtreeVars: string[];
	/** Index-aligned with the branches; `null` for a branch with no patchable content. */
	branches: (PatchBranch | null)[];
}

/** One generated `BackflipPatch_<id>` class. */
export interface PatchBranch {
	/** `BackflipPatch_MyElement` at the root, `BackflipPatch_<setId>_<branchIndex>` below it. */
	className: string;
	sites: BfidSite[];
	sets: IfSetPatchSite[];
	/** Live vars this class's `update` switches over. */
	vars: string[];
}

export function classNameFor(partialName: string): string {
	const parts = partialName.split('-').filter(s => s.length > 0);
	const camel = parts.map(s => s[0].toUpperCase() + s.slice(1)).join('');
	return 'Backflip' + camel;
}

/** The root patch-branch class name, paralleling `classNameFor` (`Backflip` → `BackflipPatch_`). */
export function patchClassNameFor(partialName: string): string {
	return 'BackflipPatch_' + classNameFor(partialName).slice('Backflip'.length);
}

export function sanitizeAttrName(name: string): string {
	return name.replace(/[^A-Za-z0-9_]/g, '_');
}

/**
 * Emit the whole cluster for one partial: the module-level `bfif_<setId>` snapshot
 * consts (from every set in the tree), each `BackflipPatch_*` class depth-first, and
 * finally the thin `export class BackflipMyElement` shell. Returns null when the root
 * branch has nothing to patch.
 */
export function generateClassForPartial(
	partialName: string,
	bAttrs: { name: string; isBool: boolean }[],
	root: PatchBranch,
): string | null {
	if (root.sites.length === 0 && root.sets.length === 0) return null;

	const allSets = collectAllSets(root);
	const consts = allSets.map(s => `const ${ifConstName(s.setId)} = ${s.snapshot};`);
	const patchClasses = emitPatchBranch(root);
	const shell = genElementShell(partialName, root.className, bAttrs);

	const parts: string[] = [];
	if (consts.length) parts.push(consts.join('\n'), '');
	parts.push(patchClasses, '', shell);
	return parts.join('\n');
}

/**
 * Assemble the module. `renderImportPath` is the specifier for the JS runtime's
 * `render.js`; pass it only when a class in this file actually uses an if-set.
 */
export function generateFile(classes: (string | null)[], renderImportPath?: string): string {
	const kept = classes.filter((c): c is string => c !== null);
	if (kept.length === 0) return '';
	const header = '// Generated by BackflipHTML dom-patch — do not edit.';
	const imports = renderImportPath !== undefined
		? [`import { render } from '${renderImportPath}';`, '']
		: [];
	return [header, '', ...imports, ...kept.flatMap(c => [c, ''])].join('\n').trimEnd() + '\n';
}

// Every set in the tree, depth-first (parents before their children's sets).
function collectAllSets(branch: PatchBranch): IfSetPatchSite[] {
	const out: IfSetPatchSite[] = [];
	for (const s of branch.sets) {
		out.push(s);
		for (const child of s.branches) {
			if (child) out.push(...collectAllSets(child));
		}
	}
	return out;
}

// Emit this patch-branch class and, depth-first, every descendant branch class.
function emitPatchBranch(branch: PatchBranch): string {
	const chunks = [genPatchClass(branch)];
	for (const s of branch.sets) {
		for (const child of s.branches) {
			if (child) chunks.push(emitPatchBranch(child));
		}
	}
	return chunks.join('\n\n');
}

// --- the patch-branch class ------------------------------------------------

function genPatchClass(branch: PatchBranch): string {
	const { className, sites, sets, vars } = branch;

	// sel_ per unique bfid, across both site targets and set targets.
	const bfidOrder: string[] = [];
	const seenBfid = new Set<string>();
	const noteBfid = (t: PatchTarget) => {
		if (t.kind !== 'bfid-element' || seenBfid.has(t.bfid)) return;
		seenBfid.add(t.bfid);
		bfidOrder.push(t.bfid);
	};
	for (const s of sites) noteBfid(s.target);
	for (const s of sets) noteBfid(s.target);

	// bc_ per unique fn name.
	const bcKeys = new Set<string>();
	const bcMethods: string[] = [];
	for (const s of sites) {
		const fnName = bcFnNameForSite(s);
		if (bcKeys.has(fnName)) continue;
		bcKeys.add(fnName);
		bcMethods.push(genBcMethod(fnName, s));
	}

	// Sites grouped per live var (a set contributes its condition + subtree vars).
	const sitesByVar = new Map<string, BfidSite[]>();
	for (const s of sites) {
		for (const v of s.backcode.liveVars) {
			if (!sitesByVar.has(v)) sitesByVar.set(v, []);
			sitesByVar.get(v)!.push(s);
		}
	}
	const setsByVar = new Map<string, IfSetPatchSite[]>();
	for (const s of sets) {
		for (const v of new Set([...s.ifSet.liveVars, ...s.subtreeVars])) {
			if (!setsByVar.has(v)) setsByVar.set(v, []);
			setsByVar.get(v)!.push(s);
		}
	}

	const selMethods = bfidOrder.map(genSelMethod);
	const branchMethods = sets.map(genBranchMethod);
	const getCreateMethods = sets.map(s => genGetCreateMethod(s));
	const renderIfMethods = sets.map(s => genRenderIfMethod(s, className));
	const mutateMethods = vars.map(v =>
		genMutateMethod(v, sitesByVar.get(v) ?? [], setsByVar.get(v) ?? [], className));

	// The child-range replace helper is needed by print sites and if-sets alike.
	const needsReplace = sets.length > 0 || sites.some(s => s.backcode.site.kind === 'print');
	const helperMethods = needsReplace ? [genReplaceBetweenMethod(className)] : [];

	const methods = [
		genConstructor(sets),
		'',
		...selMethods,
		...(selMethods.length ? [''] : []),
		...bcMethods,
		...(bcMethods.length ? [''] : []),
		...(branchMethods.length ? [...branchMethods, ''] : []),
		...(getCreateMethods.length ? [...getCreateMethods, ''] : []),
		...(renderIfMethods.length ? [...renderIfMethods, ''] : []),
		...mutateMethods,
		...(mutateMethods.length ? [''] : []),
		...(helperMethods.length ? [...helperMethods, ''] : []),
		genUpdate(vars),
	].join('\n');

	return `class ${className} {\n${methods}\n}`;
}

// The constructor keeps the ref element and seeds each owned set: it stores the
// active branch index (computed, not rendered — the server already emitted the
// right branch), a branch-index → child-instance map, and eagerly creates the
// child for the active branch.
function genConstructor(sets: IfSetPatchSite[]): string {
	const lines = ['\t\tthis.ref_elem = ref_elem;'];
	for (const s of sets) {
		lines.push(`\t\tthis.${activeIndexField(s.setId)} = this.${branchFnName(s.setId)}(data);`);
		lines.push(`\t\tthis.${pbMapField(s.setId)} = new Map();`);
		lines.push(`\t\tthis.${getCreateFnName(s.setId)}(this.${activeIndexField(s.setId)}, data);`);
	}
	return `\tconstructor(ref_elem, data) {\n${lines.join('\n')}\n\t}`;
}

// Symbols an if-set owns, all keyed off its leading marker's bfid.
function ifConstName(setId: string): string { return `bfif_${setId}`; }
function branchFnName(setId: string): string { return `branch_${setId}`; }
function renderIfFnName(setId: string): string { return `renderIf_${setId}`; }
function getCreateFnName(setId: string): string { return `getCreatePatchBranch_${setId}`; }
function activeIndexField(setId: string): string { return `if_${setId}`; }
function pbMapField(setId: string): string { return `if_pb_${setId}`; }

function selFnName(bfid: string): string { return `sel_${bfid}`; }
function mutateFnName(varName: string): string { return `mutate_${varName}`; }

function genSelMethod(bfid: string): string {
	return `\t${selFnName(bfid)}() { return this.ref_elem.querySelector('[data-bfid="${bfid}"]'); }`;
}

// The JS expression that resolves a target element within this class.
function targetExpr(t: PatchTarget): string {
	return t.kind === 'ref-element' ? 'this.ref_elem' : `this.${selFnName(t.bfid)}()`;
}

// Stable grouping key for a patch target.
function targetKey(t: PatchTarget): string {
	return t.kind === 'ref-element' ? 'ref' : `bf:${t.bfid}`;
}

// Returns the index of the winning branch, or -1 when none matches (a set with
// no b-else whose conditions are all falsy renders nothing).
function genBranchMethod(s: IfSetPatchSite): string {
	const vars = s.ifSet.liveVars;
	const destructure = vars.length === 0 ? '' : `\t\tconst { ${vars.join(', ')} } = data;\n`;
	const lines: string[] = [];
	let hasElse = false;
	s.ifSet.node.branches.forEach((b, i) => {
		if (hasElse) return;   // nothing can follow a b-else
		if (b.condition) {
			lines.push(`\t\tif (${generateStatement(b.condition.expr!)}) return ${i};`);
		} else {
			lines.push(`\t\treturn ${i};`);   // b-else — always wins if reached
			hasElse = true;
		}
	});
	if (!hasElse) lines.push('\t\treturn -1;');
	return `\t${branchFnName(s.setId)}(data) {\n${destructure}${lines.join('\n')}\n\t}`;
}

// Lazily construct (and memoize) the child patch-branch for a given branch index.
// Only branches with patchable content get a case; others leave `pb` undefined, so
// the caller (and `this.if_pb`) treats them as "no child".
function genGetCreateMethod(s: IfSetPatchSite): string {
	const map = pbMapField(s.setId);
	const ref = targetExpr(s.target);
	const cases: string[] = [];
	s.branches.forEach((child, i) => {
		if (child) cases.push(`\t\t\tcase ${i}: pb = new ${child.className}(${ref}, data); break;`);
	});
	return [
		`\t${getCreateFnName(s.setId)}(branch_i, data) {`,
		`\t\tif (this.${map}.has(branch_i)) return this.${map}.get(branch_i);`,
		'\t\tlet pb;',
		'\t\tswitch (branch_i) {',
		...cases,
		'\t\t}',
		`\t\tif (pb) this.${map}.set(branch_i, pb);`,
		'\t\treturn pb;',
		'\t}',
	].join('\n');
}

// Re-render the set only when the winning branch actually changed. Returns true if
// it re-rendered, false otherwise. On a real swap it evicts the old branch's child
// instance and creates the new one. The fragment is built with
// createContextualFragment against the target element so the branch HTML is parsed
// in its real parent context (a <tr> under a <tbody> survives).
function genRenderIfMethod(s: IfSetPatchSite, className: string): string {
	const idxField = activeIndexField(s.setId);
	const map = pbMapField(s.setId);
	return [
		`\t${renderIfFnName(s.setId)}(data) {`,
		`\t\tconst idx = this.${branchFnName(s.setId)}(data);`,
		`\t\tif (idx === this.${idxField}) return false;`,
		`\t\tconst elem = ${targetExpr(s.target)};`,
		'\t\tif (!elem) {',
		`\t\t\t${genMissingElementError(s.target, className)}`,
		'\t\t\treturn false;',
		'\t\t}',
		`\t\tthis.${map}.delete(this.${idxField});`,
		`\t\tthis.${idxField} = idx;`,
		'\t\tconst range = document.createRange();',
		'\t\trange.selectNodeContents(elem);',
		`\t\tconst frag = range.createContextualFragment(render(${ifConstName(s.setId)}, data));`,
		`\t\tthis.replaceBetween(elem, '${commentMarker(s.setId)}', '${commentMarker(s.endId)}', frag);`,
		`\t\tthis.${getCreateFnName(s.setId)}(idx, data);`,
		'\t\treturn true;',
		'\t}',
	].join('\n');
}

function genBcMethod(fnName: string, s: BfidSite): string {
	const expr = generateStatement(s.backcode.parsed.expr!);
	const vars = s.backcode.parsed.vars;
	const destructure = vars.length === 0 ? '' : `\t\tconst { ${vars.join(', ')} } = data;\n`;
	return `\t${fnName}(data) {\n${destructure}\t\treturn ${expr};\n\t}`;
}

function genMutateMethod(
	varName: string,
	varSites: BfidSite[],
	varSets: IfSetPatchSite[],
	className: string,
): string {
	// Set handling runs first: a swap replaces whole subtrees, so any attr/print site
	// that lives in a branch must be patched against the DOM that results. For a set
	// driven by `varName`:
	//   - condition var only → re-render (fresh render already reflects the data).
	//   - subtree var only   → forward into the active child (branch cannot have moved).
	//   - both               → re-render *or* forward, never both.
	const setLines: string[] = [];
	for (const s of varSets) {
		const inCond = s.ifSet.liveVars.includes(varName);
		const inSub = s.subtreeVars.includes(varName);
		const map = pbMapField(s.setId);
		const idx = activeIndexField(s.setId);
		const forward = [
			`\t\t\tconst pb = this.${map}.get(this.${idx});`,
			`\t\t\tif (pb) pb.update('${varName}', data);`,
		];
		if (inCond && inSub) {
			setLines.push(`\t\tif (!this.${renderIfFnName(s.setId)}(data)) {`, ...forward, '\t\t}');
		} else if (inCond) {
			setLines.push(`\t\tthis.${renderIfFnName(s.setId)}(data);`);
		} else {
			setLines.push('\t\t{', ...forward, '\t\t}');
		}
	}

	if (varSites.length === 0) {
		return `\t${mutateFnName(varName)}(data) {\n${setLines.join('\n')}\n\t}`;
	}

	// Group sites by target element so each `elem = …` lookup and its null guard is
	// emitted once per mutate fn. A null lookup means the rendered DOM diverged from
	// the compiled template, so the guard logs instead of silently skipping.
	const byTarget = new Map<string, { target: PatchTarget; sites: BfidSite[] }>();
	for (const s of varSites) {
		const key = targetKey(s.target);
		let group = byTarget.get(key);
		if (!group) {
			group = { target: s.target, sites: [] };
			byTarget.set(key, group);
		}
		group.sites.push(s);
	}

	const body: string[] = [...setLines, '\t\tlet elem;'];
	for (const { target, sites } of byTarget.values()) {
		body.push(`\t\telem = ${targetExpr(target)};`);
		body.push('\t\tif (elem) {');
		for (const s of sites) body.push(genSiteUpdate(s));
		body.push('\t\t} else {');
		body.push(`\t\t\t${genMissingElementError(target, className)}`);
		body.push('\t\t}');
	}
	return `\t${mutateFnName(varName)}(data) {\n${body.join('\n')}\n\t}`;
}

// Per-class marker-range replace, shared by 'print' sites and if-sets. Finds the
// two marker comments among `parent`'s direct children, removes every node strictly
// between them, and inserts `node` before the closing marker.
function genReplaceBetweenMethod(className: string): string {
	return [
		'\treplaceBetween(parent, startMarker, endMarker, node) {',
		'\t\tlet start = null, end = null;',
		'\t\tfor (const child of parent.childNodes) {',
		'\t\t\tif (child.nodeType !== 8) continue;',
		'\t\t\tif (child.nodeValue === startMarker) start = child;',
		'\t\t\telse if (child.nodeValue === endMarker) end = child;',
		'\t\t}',
		'\t\tif (!start || !end) {',
		`\t\t\tconsole.error('BackflipHTML ${className}: comment markers not found; skipping update', parent);`,
		'\t\t\treturn;',
		'\t\t}',
		'\t\tlet n = start.nextSibling;',
		'\t\twhile (n && n !== end) {',
		'\t\t\tconst next = n.nextSibling;',
		'\t\t\tparent.removeChild(n);',
		'\t\t\tn = next;',
		'\t\t}',
		'\t\tparent.insertBefore(node, end);',
		'\t}',
	].join('\n');
}

function genMissingElementError(target: PatchTarget, className: string): string {
	if (target.kind === 'ref-element') {
		return `console.error('BackflipHTML ${className}: ref element not found; skipping update', this.ref_elem);`;
	}
	return `console.error('BackflipHTML ${className}: element [data-bfid="${target.bfid}"] not found; skipping update', this.ref_elem);`;
}

function bcFnNameForSite(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr': {
			// An 'attr' site always patches a descendant element (never the ref element).
			if (s.target.kind !== 'bfid-element') {
				throw new Error("dom-patch codegen: 'attr' site must target a bfid element");
			}
			return `bc_${s.target.bfid}_${sanitizeAttrName(inner.attr.name)}`;
		}
		case 'definition-root-attr':
			// ref-element target: no bfid, so use a fixed 'ce' infix. bfids are always
			// 'bf'-prefixed, so `bc_ce_…` can never collide with `bc_<bfid>_…`; two
			// def-root attrs with the same name are already rejected by the compiler.
			return `bc_ce_${sanitizeAttrName(inner.attr.name)}`;
		case 'print': {
			// Keyed off the (unique) leading marker id, so each print gets its own bc fn.
			if (!s.comments) {
				throw new Error("dom-patch codegen: 'print' site is missing its comment markers");
			}
			return `bc_print_${sanitizeAttrName(s.comments.startId)}`;
		}
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add a bc-name scheme when wiring this kind in.`);
	}
}

function genSiteUpdate(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr':
		case 'definition-root-attr': {
			const fn = bcFnNameForSite(s);
			const dom = inner.attr.name;
			if (inner.attr.isBoolean) {
				return `\t\t\tif (this.${fn}(data)) elem.setAttribute('${dom}', ''); else elem.removeAttribute('${dom}');`;
			}
			return `\t\t\telem.setAttribute('${dom}', String(this.${fn}(data)));`;
		}
		case 'print': {
			if (!s.comments) {
				throw new Error("dom-patch codegen: 'print' site is missing its comment markers");
			}
			const fn = bcFnNameForSite(s);
			const start = commentMarker(s.comments.startId);
			const end = commentMarker(s.comments.endId);
			return `\t\t\tthis.replaceBetween(elem, '${start}', '${end}', document.createTextNode(String(this.${fn}(data))));`;
		}
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add an emit branch when wiring this kind in.`);
	}
}

function genUpdate(vars: string[]): string {
	const cases = vars.map(v =>
		`\t\t\tcase '${v}': this.${mutateFnName(v)}(data); break;`
	);
	return `\tupdate(varname, data) {\n\t\tswitch (varname) {\n${cases.join('\n')}\n\t\t}\n\t}`;
}

// --- the thin BackflipMyElement shell --------------------------------------

function genElementShell(
	partialName: string,
	rootPatchClass: string,
	bAttrs: { name: string; isBool: boolean }[],
): string {
	const className = classNameFor(partialName);
	const collectLines = bAttrs.map(b =>
		b.isBool
			? `\t\t\t${b.name}: this.ce.hasAttribute('${b.name}'),`
			: `\t\t\t${b.name}: this.ce.getAttribute('${b.name}') ?? '',`
	);
	return [
		`export class ${className} {`,
		'\tconstructor(ce) {',
		'\t\tthis.ce = ce;',
		`\t\tthis.pb = new ${rootPatchClass}(this.ce, this.collectData());`,
		'\t}',
		'\tcollectData() {',
		'\t\treturn {',
		...collectLines,
		'\t\t};',
		'\t}',
		'\tupdate(varname) {',
		'\t\tthis.pb.update(varname, this.collectData());',
		'\t}',
		'}',
	].join('\n');
}
