import { generateStatement } from '../js/generatejs.js';
import type { BackcodeSite } from './collect.js';

export interface BfidSite {
	bfid: string;
	backcode: BackcodeSite;
}

export function classNameFor(partialName: string): string {
	const parts = partialName.split('-').filter(s => s.length > 0);
	const camel = parts.map(s => s[0].toUpperCase() + s.slice(1)).join('');
	return 'Backflip' + camel;
}

export function sanitizeAttrName(name: string): string {
	return name.replace(/[^A-Za-z0-9_]/g, '_');
}

export function generateClassForPartial(
	partialName: string,
	bAttrs: { name: string; isBool: boolean }[],
	sites: BfidSite[],
): string | null {
	if (sites.length === 0) return null;

	const className = classNameFor(partialName);

	// One sel_ per unique bfid (preserving first-seen order).
	const bfidOrder: string[] = [];
	const seenBfid = new Set<string>();
	for (const s of sites) {
		if (!seenBfid.has(s.bfid)) {
			seenBfid.add(s.bfid);
			bfidOrder.push(s.bfid);
		}
	}

	// One bc_ per unique (bfid, kind-specific suffix). For attr sites the suffix
	// is the sanitized attr name; new kinds get their own suffix scheme.
	const bcKeys = new Set<string>();
	const bcMethods: string[] = [];
	for (const s of sites) {
		const fnName = bcFnNameForSite(s);
		if (bcKeys.has(fnName)) continue;
		bcKeys.add(fnName);
		bcMethods.push(genBcMethod(fnName, s));
	}

	// Group sites per live variable (order = first-seen across sites).
	const sitesByVar = new Map<string, BfidSite[]>();
	const varOrder: string[] = [];
	for (const s of sites) {
		for (const v of s.backcode.liveVars) {
			if (!sitesByVar.has(v)) {
				sitesByVar.set(v, []);
				varOrder.push(v);
			}
			sitesByVar.get(v)!.push(s);
		}
	}

	const selMethods = bfidOrder.map(genSelMethod);
	const mutateMethods = varOrder.map(v => genMutateMethod(v, sitesByVar.get(v)!));
	const collect = genCollectData(bAttrs);
	const update = genUpdate(varOrder);

	const methods = [
		'\tconstructor(ce) { this.ce = ce; }',
		'',
		...selMethods,
		'',
		...bcMethods,
		'',
		...mutateMethods,
		'',
		collect,
		'',
		update,
	].join('\n');

	return `class ${className} {\n${methods}\n}`;
}

export function generateFile(classes: (string | null)[]): string {
	const kept = classes.filter((c): c is string => c !== null);
	if (kept.length === 0) return '';
	const header = '// Generated by BackflipHTML dom-patch — do not edit.';
	return [header, '', ...kept.flatMap(c => [c, ''])].join('\n').trimEnd() + '\n';
}

function bcFnNameForSite(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr':
			return `bc_${s.bfid}_${sanitizeAttrName(inner.attr.name)}`;
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add a bc-name scheme when wiring this kind in.`);
	}
}

function selFnName(bfid: string): string {
	return `sel_${bfid}`;
}

function mutateFnName(varName: string): string {
	return `mutate_${varName}`;
}

function genSelMethod(bfid: string): string {
	return `\t${selFnName(bfid)}() { return this.ce.querySelector('[data-bfid="${bfid}"]'); }`;
}

function genBcMethod(fnName: string, s: BfidSite): string {
	const expr = generateStatement(s.backcode.parsed.expr!);
	const vars = s.backcode.parsed.vars;
	const destructure = vars.length === 0 ? '' : `\t\tconst { ${vars.join(', ')} } = data;\n`;
	return `\t${fnName}(data) {\n${destructure}\t\treturn ${expr};\n\t}`;
}

function genMutateMethod(varName: string, varSites: BfidSite[]): string {
	// Group by bfid so sel_<bfid>() is called once per element per mutate fn.
	const byBfid = new Map<string, BfidSite[]>();
	const bfidOrder: string[] = [];
	for (const s of varSites) {
		if (!byBfid.has(s.bfid)) {
			byBfid.set(s.bfid, []);
			bfidOrder.push(s.bfid);
		}
		byBfid.get(s.bfid)!.push(s);
	}

	const body: string[] = ['\t\tlet elem;'];
	for (const bfid of bfidOrder) {
		body.push(`\t\telem = this.${selFnName(bfid)}();`);
		for (const s of byBfid.get(bfid)!) {
			body.push(genSiteUpdate(s));
		}
	}
	return `\t${mutateFnName(varName)}(data) {\n${body.join('\n')}\n\t}`;
}

function genSiteUpdate(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr': {
			const fn = bcFnNameForSite(s);
			const dom = inner.attr.name;
			if (inner.attr.isBoolean) {
				return `\t\tif (elem) { if (this.${fn}(data)) elem.setAttribute('${dom}', ''); else elem.removeAttribute('${dom}'); }`;
			}
			return `\t\tif (elem) elem.setAttribute('${dom}', String(this.${fn}(data)));`;
		}
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add an emit branch when wiring this kind in.`);
	}
}

function genCollectData(bAttrs: { name: string; isBool: boolean }[]): string {
	const lines = bAttrs.map(b =>
		b.isBool
			? `\t\t\t${b.name}: this.ce.hasAttribute('${b.name}'),`
			: `\t\t\t${b.name}: this.ce.getAttribute('${b.name}') ?? '',`
	);
	return `\tcollectData() {\n\t\treturn {\n${lines.join('\n')}\n\t\t};\n\t}`;
}

function genUpdate(varOrder: string[]): string {
	const cases = varOrder.map(v =>
		`\t\t\tcase '${v}': this.${mutateFnName(v)}(this.collectData()); break;`
	);
	return `\tupdate(varname) {\n\t\tswitch (varname) {\n${cases.join('\n')}\n\t\t}\n\t}`;
}
