import { generateStatement } from '../js/generatejs.js';
import type { BackcodeSite } from './collect.js';

/**
 * Which DOM node a patch site updates.
 *  - `bfid-element`: an element inside the partial body. Located at runtime via
 *    `querySelector('[data-bfid="<bfid>"]')`, so it carries the generated bfid.
 *  - `this-element`: the custom element itself. The runtime already holds a
 *    direct reference (`this.ce`), so there is no bfid and no querySelector.
 */
export type PatchTarget =
	| { kind: 'bfid-element'; bfid: string }
	| { kind: 'this-element' };

export interface BfidSite {
	target: PatchTarget;
	backcode: BackcodeSite;
}

export function classNameFor(partialName: string): string {
	const parts = partialName.split('-').filter(s => s.length > 0);
	const camel = parts.map(s => s[0].toUpperCase() + s.slice(1)).join('');
	return 'Backflip' + camel;
}

export function sanitizeAttrName(name: string): string {
	return name.replace(/[^A-Za-z0-9_]/g, '_');
}

export function generateClassForPartial(
	partialName: string,
	bAttrs: { name: string; isBool: boolean }[],
	sites: BfidSite[],
): string | null {
	if (sites.length === 0) return null;

	const className = classNameFor(partialName);

	// One sel_ per unique bfid (preserving first-seen order). Sites that target
	// the custom element itself have no bfid and no sel_ method.
	const bfidOrder: string[] = [];
	const seenBfid = new Set<string>();
	for (const s of sites) {
		if (s.target.kind !== 'bfid-element') continue;
		if (!seenBfid.has(s.target.bfid)) {
			seenBfid.add(s.target.bfid);
			bfidOrder.push(s.target.bfid);
		}
	}

	// One bc_ per unique (bfid, kind-specific suffix). For attr sites the suffix
	// is the sanitized attr name; new kinds get their own suffix scheme.
	const bcKeys = new Set<string>();
	const bcMethods: string[] = [];
	for (const s of sites) {
		const fnName = bcFnNameForSite(s);
		if (bcKeys.has(fnName)) continue;
		bcKeys.add(fnName);
		bcMethods.push(genBcMethod(fnName, s));
	}

	// Group sites per live variable (order = first-seen across sites).
	const sitesByVar = new Map<string, BfidSite[]>();
	const varOrder: string[] = [];
	for (const s of sites) {
		for (const v of s.backcode.liveVars) {
			if (!sitesByVar.has(v)) {
				sitesByVar.set(v, []);
				varOrder.push(v);
			}
			sitesByVar.get(v)!.push(s);
		}
	}

	const selMethods = bfidOrder.map(genSelMethod);
	const mutateMethods = varOrder.map(v => genMutateMethod(v, sitesByVar.get(v)!, className));
	const collect = genCollectData(bAttrs);
	const update = genUpdate(varOrder);

	const methods = [
		'\tconstructor(ce) { this.ce = ce; }',
		'',
		...selMethods,
		'',
		...bcMethods,
		'',
		...mutateMethods,
		'',
		collect,
		'',
		update,
	].join('\n');

	return `class ${className} {\n${methods}\n}`;
}

export function generateFile(classes: (string | null)[]): string {
	const kept = classes.filter((c): c is string => c !== null);
	if (kept.length === 0) return '';
	const header = '// Generated by BackflipHTML dom-patch — do not edit.';
	return [header, '', ...kept.flatMap(c => [c, ''])].join('\n').trimEnd() + '\n';
}

function bcFnNameForSite(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr': {
			// An 'attr' site always patches a body element (target assigned in nodes2patch.ts).
			if (s.target.kind !== 'bfid-element') {
				throw new Error("dom-patch codegen: 'attr' site must target a body element");
			}
			return `bc_${s.target.bfid}_${sanitizeAttrName(inner.attr.name)}`;
		}
		case 'definition-root-attr':
			// this-element target: no bfid, so use a fixed 'ce' infix instead.
			// `bc_ce_<attr>` shares a namespace with bfid-element names `bc_<bfid>_<attr>`
			// but cannot collide with them: bfids are generated with the 'bf' prefix
			// (see makeBfidGen in bfid.ts), so a `bc_bf…` name is never a `bc_ce…` name.
			// The only remaining collision source — two def-root attrs with the same
			// name — is already rejected by the compiler.
			return `bc_ce_${sanitizeAttrName(inner.attr.name)}`;
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add a bc-name scheme when wiring this kind in.`);
	}
}

function selFnName(bfid: string): string {
	return `sel_${bfid}`;
}

// Stable grouping key for a patch target. bfid-element keys are namespaced with
// 'bf:' so they can never equal the this-element key 'ce'.
function targetKey(t: PatchTarget): string {
	return t.kind === 'this-element' ? 'ce' : `bf:${t.bfid}`;
}

function mutateFnName(varName: string): string {
	return `mutate_${varName}`;
}

function genSelMethod(bfid: string): string {
	return `\t${selFnName(bfid)}() { return this.ce.querySelector('[data-bfid="${bfid}"]'); }`;
}

function genBcMethod(fnName: string, s: BfidSite): string {
	const expr = generateStatement(s.backcode.parsed.expr!);
	const vars = s.backcode.parsed.vars;
	const destructure = vars.length === 0 ? '' : `\t\tconst { ${vars.join(', ')} } = data;\n`;
	return `\t${fnName}(data) {\n${destructure}\t\treturn ${expr};\n\t}`;
}

function genMutateMethod(varName: string, varSites: BfidSite[], className: string): string {
	// Group sites by target element so each `elem = …` lookup and its null guard is
	// emitted once per mutate fn. All this-element sites land in one group (there is
	// only one ce). A null lookup means the rendered DOM diverged from the compiled
	// template, so the guard logs instead of silently skipping the update.
	const byTarget = new Map<string, { target: PatchTarget; sites: BfidSite[] }>();
	for (const s of varSites) {
		const key = targetKey(s.target);
		let group = byTarget.get(key);
		if (!group) {
			group = { target: s.target, sites: [] };
			byTarget.set(key, group);
		}
		group.sites.push(s);
	}

	const body: string[] = ['\t\tlet elem;'];
	for (const { target, sites } of byTarget.values()) {
		body.push(target.kind === 'this-element'
			? `\t\telem = this.ce;`
			: `\t\telem = this.${selFnName(target.bfid)}();`);
		body.push('\t\tif (elem) {');
		for (const s of sites) {
			body.push(genSiteUpdate(s));
		}
		body.push('\t\t} else {');
		body.push(`\t\t\t${genMissingElementError(target, className)}`);
		body.push('\t\t}');
	}
	return `\t${mutateFnName(varName)}(data) {\n${body.join('\n')}\n\t}`;
}

function genMissingElementError(target: PatchTarget, className: string): string {
	if (target.kind === 'this-element') {
		return `console.error('BackflipHTML ${className}: host element not found; skipping update');`;
	}
	return `console.error('BackflipHTML ${className}: element [data-bfid="${target.bfid}"] not found; skipping update', this.ce);`;
}

function genSiteUpdate(s: BfidSite): string {
	const inner = s.backcode.site;
	switch (inner.kind) {
		case 'attr':
		case 'definition-root-attr': {
			const fn = bcFnNameForSite(s);
			const dom = inner.attr.name;
			if (inner.attr.isBoolean) {
				return `\t\t\tif (this.${fn}(data)) elem.setAttribute('${dom}', ''); else elem.removeAttribute('${dom}');`;
			}
			return `\t\t\telem.setAttribute('${dom}', String(this.${fn}(data)));`;
		}
		default:
			throw new Error(`dom-patch codegen: unsupported site kind '${inner.kind}' — add an emit branch when wiring this kind in.`);
	}
}

function genCollectData(bAttrs: { name: string; isBool: boolean }[]): string {
	const lines = bAttrs.map(b =>
		b.isBool
			? `\t\t\t${b.name}: this.ce.hasAttribute('${b.name}'),`
			: `\t\t\t${b.name}: this.ce.getAttribute('${b.name}') ?? '',`
	);
	return `\tcollectData() {\n\t\treturn {\n${lines.join('\n')}\n\t\t};\n\t}`;
}

function genUpdate(varOrder: string[]): string {
	const cases = varOrder.map(v =>
		`\t\t\tcase '${v}': this.${mutateFnName(v)}(this.collectData()); break;`
	);
	return `\tupdate(varname) {\n\t\tswitch (varname) {\n${cases.join('\n')}\n\t\t}\n\t}`;
}
