export { compileDirectory } from './compiler/partials.js';
export type { CompiledDirectory } from './compiler/partials.js';
export { fileToJsModule } from './compiler/generate/js/nodes2js.js';
export { fileToPhpFile } from './compiler/generate/php/nodes2php.js';
export { BackflipError } from './compiler/errors.js';
export { loadConfig, resolveConfigRoot, CONFIG_FILENAME } from './compiler/config.js';
export type { BackflipConfig } from './compiler/config.js';
export { collectSlots } from './compiler/compiler.js';
export type { SourceLoc, CompiledFile, RootTNode, TNode, PartialRefTNode, ForTNode, IfTNode, IfBranch, SlotTNode, PrintTNode, RawTNode, AttrBindTNode, PartialMeta } from './compiler/compiler.js';
export { inferDataShape, inferFreeVars } from './compiler/data-shape.js';
export type { DataShape, UsageKind } from './compiler/data-shape.js';
export { previewPartial } from './preview/preview.js';
export type { PreviewOptions, PreviewResult } from './preview/preview.js';
